demo: true
clearForFrames: true
logsize: 50
maintainerMainUser: ubuntu
tmuxName: server
jarName: spigot
maintainerPath: /home/ubuntu
useSshUsers: false
sshUsers:
    Username1: THISISAKEY_THISISASECONDKEYFORTHEFIRSTUSER 
    Username2: NULL_RESEVES_NAMES_UNTIL_SETUP
    Username3: NULL
    Username4: NULL
# To get the key for Maintainer login, do the following:
# Run:
# echo $SSH_CONNECTION
# Then run:
# sudo grep -F ' from <first IP in output above> port <port (second number from output above)> ' /var/log/auth.log | grep ssh

# minecraft-server-maintaner - Level up your Minecraft Server Maintanance and Control!
# Copyright (C) 2023  Viktor Tkachuk, aka. VicKetchup, from Ketchup&Co.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.